### ISSUE TITLE
Add 'contact us' section in footer style guide -design

### ISSUE THREAD

**Issue by eloketobe** [zuri-training/anima_lib_team98#21]
The section should contain the contact information and also a link to the contact page through a navigator that says "leave us a messge"

**Comment by starjosh48** [comment]
![Property 1=HiFi](https://user-images.githubusercontent.com/58112128/182708080-83ccc18c-4f2b-493e-9729-7780dfcd7c52.jpg)
The contact information has been added

**Comment by eloketobe** [comment]
Welldone
