### ISSUE TITLE
Round up documentation hifi -design

### ISSUE THREAD

**Issue by eloketobe** [zuri-training/anima_lib_team98#23]

**Comment by Voiced-debug** [comment]
The documentation page is meant to provide insight as to how the animation library can help developers, how to use it and how to contribute to the project. I added some microinteraction to each section of the page. 

Here's a link to the hifi:
https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=878%3A2499
