### ISSUE TITLE
Create navigation to FAQ page - design

### ISSUE THREAD

**Issue by eloketobe** [zuri-training/anima_lib_team98#32]
Add a navigation link to the About us page and contact us pages that link to the FAQ page to help users easily navigate to the FAQ page.
@Ashabiade handle About Us 
@starjosh48 handle contact us
Suggestion: you could use a tertiary button with some text prompt on it

**Comment by starjosh48** [comment]
I have added a navigation link that will link users to the FAQ page on the contact us page using a tertiary button for the FAQ text. 
![Contact us (1)](https://user-images.githubusercontent.com/58112128/182709149-495a4b84-c3bb-4e59-a085-4d9629719dae.jpg)

**Comment by eloketobe** [comment]
Replace `Frequently asked questions` with `FAQ`

**Comment by starjosh48** [comment]
![Contact us](https://user-images.githubusercontent.com/58112128/182731388-91b22254-158d-4071-838d-7a01639d0f99.jpg)
Replaced 😊

**Comment by eloketobe** [comment]
great welldone
waiting on you @Ashabiade

**Comment by Ashabiade** [comment]
I added a navigation link using a tertiary button for the FAQ text on the About Us page so users can easily navigate to the FAQ page.
![About us page (1)](https://user-images.githubusercontent.com/105219418/182795677-47df7d90-7e13-4c51-926b-526f0950a3a7.png)
