### ISSUE TITLE
Prototype an authentication flow that would demonstrate how users navigate our site to get authenticated - design

### ISSUE THREAD

**Issue by eloketobe** [zuri-training/anima_lib_team98#52]

**Comment by Ashabiade** [comment]
I prototyped the create account and email sent page to demonstrate how users navigate our site to get authenticated. https://www.figma.com/proto/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=2439%3A12140&scaling=scale-down&page-id=2439%3A12101&starting-point-node-id=2439%3A12140&show-proto-sidebar=1

**Comment by starjosh48** [comment]
I protoyped the sign in page for users authentication
[link to the prototyped sign in page](https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=2439%3A12183)

**Comment by VicRoosevelt** [comment]
I prototype the forgot password page and also the reset password page to demonstrate how users should navigate our site to get authenticated

[Link to prototype forgot password page](https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=2439%3A12229) , 

[Link to prototype reset password page](https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=2439%3A12254)
