### ISSUE TITLE
Design a `contact us` page for users to see our contact info and also leave a message-design

### ISSUE THREAD

**Issue by eloketobe** [zuri-training/anima_lib_team98#61]

**Comment by starjosh48** [comment]
I designed the contact us page and a leave message design
[Link to the contact us page](https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=2439%3A12282)
[Link to the message sent overlay](https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=2439%3A14612)

**Comment by debbyCokes** [comment]
Star josh and I worked on the contact us page so that users can interract with Animax team to get swift response to their issues.
