### ISSUE TITLE
prototype the animation library page to show some animations - design

### ISSUE THREAD

**Issue by eloketobe** [zuri-training/anima_lib_team98#63]

**Comment by TomiEtta** [comment]
In addition to designing animation page #24, I prototyped each animation and the animation preview pages/components.

Here are some of the animations I made:

1. Bouncing
2. Cloud
3. Move
4. Pulse
5. Rotate
6. Stretch
7. Alternate Colours
8. Blink

[Link to the Moving Left Animation page](https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=2682%3A11755)
