### ISSUE TITLE
Design a `download` page =design

### ISSUE THREAD

**Issue by eloketobe** [zuri-training/anima_lib_team98#64]

**Comment by TomiEtta** [comment]
The download page had to be intuitive, and informative, but not cluttered. Given that it is one of the most essential pages on the Animax site, I had to do my research and look at it from the UX standpoint. 

So what did I do?

1. I broke down the information into easily digestible bits - the goal here is to make it simple for beginner/junior developers.
2.  I also added a restart download button - this is in case the download process was unsuccessful or the user just wanted to download again. It is much better than refreshing the entire page.
3. I added important links leading to both the documentation page and FAQs which are likely something the user could search for. If we had a Help Center, that would have been one of the links.
4. And of course, letting the user know the download would automatically start. This feedback is important.

[This is the link to the Download page.](https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=2439%3A12102)
