### ISSUE TITLE
Curate a mood board to inspire the design process - design

### ISSUE THREAD

**Issue by eloketobe** [zuri-training/anima_lib_team98#65]

**Comment by TomiEtta** [comment]
This mood board was created to set the visual direction for the Animax library. 

I put together supporting imagery, including websites with interfaces that inspired our visual direction, pages with incredible UX experiences like the Air BnB authentication process, and our competitors - other popular animation sites to learn what they did best.

[This is the link to the mood board.](https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=2098%3A6675)
