### ISSUE TITLE
Prototype the documentation page to show the flow of users through the pages - design

### ISSUE THREAD

**Issue by eloketobe** [zuri-training/anima_lib_team98#78]

**Comment by Voiced-debug** [comment]
To ensure a smooth transition between each page, I prototyped the documentation pages taking into consideration the user experience. Here's the link to the prototype

[Documentation flow](https://www.figma.com/proto/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=2439%3A13346&scaling=scale-down&page-id=2439%3A12101&starting-point-node-id=2439%3A12557&show-proto-sidebar=1)
