### ISSUE TITLE
Create wireframes to serve as a skeleton for design -design

### ISSUE THREAD

**Issue by eloketobe** [zuri-training/anima_lib_team98#8]
[link to the wireframing figma file]( https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Anima-Project-Design?node-id=0%3A1 )

**Comment by princehaifan** [comment]
As a designer, my teammates and I were able to sketch and create a wireframe for Animation Library  lofi and hifi screens, to be used as a guide design system.

Below is the links

https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=604%3A980

https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=0%3A1

**Comment by Zaynabbodude** [comment]
As a designer my colleagues and I worked on creating wireframes for the features on our product, we started creating wireframes on figma but due to the limited time we couldn't complete them and decided to create the wireframes on paper as sketches.

**Comment by VicRoosevelt** [comment]
As a designer, i and my Team were able to sketch a wireframe for our Animation Library that help guide our design process. 
[Link to wireframes](https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=0%3A1).

**Comment by eloketobe** [comment]
Welldone guys

**Comment by OreRuth** [comment]
As a designer, my team and I were able to create a wireframe for subsequent lofi and hifi screens, to be used as a guide.
Below is the link to the wireframes
https://www.figma.com/file/mnP49B5GDsVrVBPIp1Q6g0/Animax-Project-Design?node-id=0%3A1
